CREATE TABLE users (
    id       integer      GENERATED BY DEFAULT AS IDENTITY,
    password varchar(255) NOT NULL,
    username varchar(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

INSERT INTO users (id, password, username)
VALUES  (1, '$2a$10$NnsTm1iEwEn29zPnx7uMdOb9R6MoybsfPtZ8XHbzSbjLSiDfyeZPu', 'user'),   -- 100
        (2, '$2a$10$2.N2cRPCl5kokGspI5mddeN0l48PwzXPEvhTwmbvKzVFzBLpWMwwe', 'user1');  -- 100