CREATE TABLE files_storage(
    id           integer GENERATED BY DEFAULT AS IDENTITY,
    date         timestamp(6),
    file_content bytea,
    file_size    bigint,
    file_title   varchar(255),
    user_id      integer REFERENCES users (id),
    PRIMARY KEY (id)
);